In [1]:
import numpy as np

foo = np.array([1, 2])
bar = np.array([3, 4])

baz = np.array([[5, 6]])
bingo = np.array([[7, 8, 9]])

题 1：vstack 两个一维数组

In [4]:
result1 = np.vstack([foo,bar])
result1

array([[1, 2],
       [3, 4]])

In [5]:
result1.shape

(2, 2)

题 2：vstack 三个数组

不能拼，因为foo, bar是一维数组


In [6]:
foo_col = foo.reshape(1,2)
bar_col = bar.reshape(1,2)

In [7]:
result2 =  np.vstack([foo_col,bar_col,baz])
result2

array([[1, 2],
       [3, 4],
       [5, 6]])

题 3：vstack baz 和 bingo

In [8]:
baz.shape

(1, 2)

In [9]:
bingo.shape

(1, 3)

不能拼，列数不同

题 4：hstack 两个一维数组

In [11]:
result3 = np.hstack([foo,bar])
result3

array([1, 2, 3, 4])

In [12]:
result3.shape

(4,)

题 5：hstack baz 和 bingo

In [14]:
result5 = np.hstack([baz, bingo])
result5

array([[5, 6, 7, 8, 9]])

In [15]:
result5.shape

(1, 5)

题 6：hstack foo 和 bingo

foo 是一维的，bingo是二维的，但是hstack没有自动转换维度的特性，所以需要用到reshape

In [16]:
foo_a = foo.reshape(1,2)

In [18]:
result6 = np.hstack([foo_a,bingo])
result6

array([[1, 2, 7, 8, 9]])

In [19]:
result6.shape

(1, 5)

题 7：stack axis=0

In [20]:
result7 = np.stack([foo,bar], axis=0)
result7

array([[1, 2],
       [3, 4]])

In [21]:
result7.shape

(2, 2)

题 8：stack axis=1

In [22]:
result8 = np.stack([foo,bar], axis=1)
result8

array([[1, 3],
       [2, 4]])

In [23]:
result8.shape

(2, 2)

题 9：stack axis=-1

In [24]:
result9 = np.stack([foo,bar], axis=-1)
result9

array([[1, 3],
       [2, 4]])

In [25]:
result9.shape

(2, 2)

是和 axis = 1 一样的 
axis=-1 表示“最后一个轴”，所以等价于 axis=1

题 10：stack shape 不一样的数组

In [26]:
foo = np.array([1, 2])
bingo = np.array([7, 8, 9])

In [27]:
result10 = np.stack([foo,bingo], axis=1)

ValueError: all input arrays must have the same shape

在stack 中 shape和维度一定要一摸一样

题 11：stack 二维数组

In [28]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [10, 20],
    [30, 40]
])

In [30]:
result11 = np.stack([A,B], axis=0)
result11

array([[[ 1,  2],
        [ 3,  4]],

       [[10, 20],
        [30, 40]]])

In [31]:
result11.shape

(2, 2, 2)

In [32]:
result12 = np.stack([A,B], axis=1)
result12.shape

(2, 2, 2)

In [33]:
A = np.ones((4, 5))
B = np.ones((4, 5))

axis=0: 2 4 5
axis=1: 4 2 5
axis=2: 4 5 2

In [34]:
A = np.ones((3, 4))
B = np.ones((3, 4))
C = np.ones((3, 4))

axis=0: 3 3 4
axis=1: 3 3 4
axis=2: 3 4 3


In [36]:
A = np.ones((2,))
B = np.ones((2,))

A.shape = (6,)
B.shape = (6,)

axis=0: 2 6
axis=1: 6 2

A.shape = (2, 5)
B.shape = (2, 5)

axis=0: 2 2 5
axis=1: 2 2 5
axis=2: 2 5 2 

A.shape = (3, 4)
B.shape = (3, 4)
C.shape = (3, 4)
D.shape = (3, 4)

axis=0: 4 3 4
axis=1: 3 4 4
axis=2: 3 4 4

题 4
A.shape = (5, 7, 9)
B.shape = (5, 7, 9)

axis=0: 2 5 7 9
axis=1: 5 2 7 9
axis=2: 5 7 2 9
axis=3: 5 7 9 2

题 5：判断能不能 stack
A.shape = (4, 5)
B.shape = (4, 6)

不能，stack 的 shape必须要完全一样

In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack([a, b]).shape （2，3）
np.hstack([a, b]).shape  （6，）
np.stack([a, b], axis=0).shape （2，3）
np.stack([a, b], axis=1).shape   （3， 2）

In [40]:
a = np.ones((1, 3))
b = np.ones((1, 2))

np.vstack([a, b]) 不行，因为是垂直堆积，增加的是行，列要一样。
np.hstack([a, b]) 可以，水平叠加，增加的是列，行要一样
np.stack([a, b]) 不行，shape必须一模一样

In [41]:
a = np.ones((2, 3))
b = np.ones((2, 3))

np.vstack([a, b]).shape  4，3
np.hstack([a, b]).shape 2，6
np.stack([a, b], axis=0).shape 2 2 3
np.stack([a, b], axis=1).shape 2 2 3
np.stack([a, b], axis=2).shape 2 3 2

hstack 全是一维数组时，结果还是一维。vstack可以自动将一维变成二维