In [1]:
import numpy as np

foo = np.array([
    [1., 2., 3.],
    [np.nan, 5., 6.],
    [np.nan, np.nan, np.nan],
    [7., 8., 9.]
])

In [2]:
np.isnan(foo)

array([[False, False, False],
       [ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [3]:
mask = np.any(np.isnan(foo), axis=1)
mask

array([False,  True,  True, False])

In [5]:
foo[mask]

array([[nan,  5.,  6.],
       [nan, nan, nan]])

题 1：检查每个元素是不是 NaN

In [6]:
foo = np.array([
    [1., 2., 3.],
    [np.nan, 5., 6.],
    [np.nan, np.nan, np.nan],
    [7., 8., 9.]
])

In [12]:
is_nan = np.isnan(foo)
is_nan

array([[False, False, False],
       [ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

题 2：找出“至少有一个 NaN 的行”

In [16]:
result2 = np.any(np.isnan(foo), axis=1)
result2

array([False,  True,  True, False])

In [17]:
foo[result2]

array([[nan,  5.,  6.],
       [nan, nan, nan]])

题 3：找出“全部都是 NaN 的行”

In [18]:
result3 = np.all(np.isnan(foo), axis=1)
result3

array([False, False,  True, False])

In [19]:
foo[result3]

array([[nan, nan, nan]])

题 4：找出“没有任何 NaN 的行”

In [24]:
result4 = ~np.any(np.isnan(foo), axis=1)
result4

array([ True, False, False,  True])

In [25]:
foo[result4]

array([[1., 2., 3.],
       [7., 8., 9.]])

题 5：找出“不是全部 NaN 的行”

In [26]:
result5 = ~np.all(np.isnan(foo), axis=1)
result5

array([ True,  True, False,  True])

In [27]:
foo[result5]

array([[ 1.,  2.,  3.],
       [nan,  5.,  6.],
       [ 7.,  8.,  9.]])

题 6：找出“至少有一个 NaN 的列”

In [28]:
result6 = np.any(np.isnan(foo), axis=0)
result6

array([ True,  True,  True])

In [30]:
foo[:,result6]

array([[ 1.,  2.,  3.],
       [nan,  5.,  6.],
       [nan, nan, nan],
       [ 7.,  8.,  9.]])

In [31]:
bar = np.array([
    [1., 2., 3., 4.],
    [5., np.nan, 7., 8.],
    [9., 10., 11., 12.]
])

题 7：找出“至少有一个 NaN 的列”

In [34]:
result7 = np.any(np.isnan(bar), axis=0)
result7

array([False,  True, False, False])

In [35]:
bar[:,result7]

array([[ 2.],
       [nan],
       [10.]])

题 8：找出“全部都是 NaN 的列”

In [39]:
baz = np.array([
    [1., np.nan, 3., np.nan],
    [5., np.nan, 7., np.nan],
    [9., np.nan, 11., np.nan]
])
result8 = np.all(np.isnan(baz), axis=0)
result8

array([False,  True, False,  True])

In [40]:
baz[:,result8]

array([[nan, nan],
       [nan, nan],
       [nan, nan]])

题 9：筛出没有任何 NaN 的行

In [45]:
data = np.array([
    [1., 2., 3.],
    [np.nan, 5., 6.],
    [7., 8., 9.],
    [np.nan, np.nan, np.nan]
])
result9 = ~np.any(np.isnan(data), axis=1)
result9

array([ True, False,  True, False])

In [46]:
data[result9]

array([[1., 2., 3.],
       [7., 8., 9.]])

题 10：筛出至少有一个 NaN 的行

In [47]:
result10 = np.any(np.isnan(data), axis=1)
result10

array([False,  True, False,  True])

In [48]:
data[result10]

array([[nan,  5.,  6.],
       [nan, nan, nan]])