In [1]:
import numpy as np

a = np.array([-3, 0, 4, 9, -10])

负数变成 -1，非负数变成 1

In [3]:
result = np.where(a < 0, 1, -1)
result

array([ 1, -1, -1, -1,  1])

In [4]:
ages = np.array([12, 18, 25, 16, 40])

年龄 >= 18 显示 'adult'，否则显示 'minor'

In [7]:
result2 = np.where(ages >=18, "adult", "minor")
result2

array(['minor', 'adult', 'adult', 'minor', 'adult'], dtype='<U5')

偶数：平方
奇数：乘以 10

In [8]:
x = np.array([2, 5, 8, 11])

In [10]:
result3 = np.where(x % 2 == 0, x*x, x * 10)
result3

array([  4,  50,  64, 110])

4温度 >= 38 显示 'fever'，否则显示 'normal'

In [12]:
temps = np.array([35, 38, 40, 36, 39])

In [13]:
result4 = np.where(temps >= 38, "fever", "normal")
result4

array(['normal', 'fever', 'fever', 'normal', 'fever'], dtype='<U6')

5.如果价格 > 100，打 8 折；
否则保持原价。

In [14]:
prices = np.array([80, 120, 300, 50])

In [18]:
result5 = np.where(prices > 100, prices * 0.8, prices)
result5

array([ 80.,  96., 240.,  50.])

6.如果成绩 < 60，加 10 分；
否则不变。

In [19]:
scores = np.array([45, 60, 72, 89, 100])

In [21]:
result6 =  np.where(scores < 60, scores + 10, scores)
result6

array([ 55,  60,  72,  89, 100])

7.库存等于 0 显示 'out'
否则显示 'available'

In [22]:
stock = np.array([0, 3, 10, 0, 5])

In [24]:
result7 = np.where(stock == 0, "out", "available")
result7

array(['out', 'available', 'available', 'out', 'available'], dtype='<U9')

8.工资 < 6000，涨 500；
否则不变。

In [25]:
salary = np.array([5000, 8000, 12000, 3000])

In [26]:
result8 = np.where(salary < 6000, salary + 500, salary)
result8

array([ 5500,  8000, 12000,  3500])

9.成绩 >= 90 显示 'A'
否则显示 'not A'

In [27]:
scores = np.array([45, 60, 72, 89, 100])

In [29]:
result9 = np.where(scores >= 90, "A", "not A")
result9

array(['not A', 'not A', 'not A', 'not A', 'A'], dtype='<U5')

10.成绩 >= 90 显示 'A'
否则，如果成绩 >= 60 显示 'pass'
否则显示 'fail'

In [30]:
scores = np.array([45, 60, 72, 89, 100])

In [33]:
result10 = np.where(scores >= 90, "A", np.where(scores >= 60, "pass", "fail"))
result10

array(['fail', 'pass', 'pass', 'pass', 'A'], dtype='<U4')

11.>= 90: 'A'
>= 80: 'B'
>= 60: 'C'
否则: 'F'

In [34]:
scores = np.array([45, 60, 72, 89, 100])

In [37]:
result11 = np.select(
    [scores >= 90, scores >= 80, scores >= 60],
    ["A", "B", "C"],
    default="F"
)
result11

array(['F', 'C', 'C', 'B', 'A'], dtype='<U1')

11.订单金额 >= 200: 运费 0
订单金额 >= 100: 运费 5
订单金额 >= 50: 运费 10
否则: 运费 20

In [38]:
amount = np.array([20, 50, 99, 100, 150, 300])

In [39]:
result12 = np.select(
    [amount>= 200, amount >= 100, amount >= 50],
    [0, 5, 50],
    default=20
)
result12

array([20, 50, 50,  5,  5,  0])

12 .积分 >= 1000: 折扣 0.7
积分 >= 500: 折扣 0.8
积分 >= 100: 折扣 0.9
否则: 折扣 1.0

In [41]:
points = np.array([0, 100, 499, 500, 999, 1000])

In [42]:
result12 = np.select(
    [points >= 1000, points >= 500, points >= 100],
    [0.7, 0.8, 0.9],
    default=1.0
)

result12

array([1. , 0.9, 0.9, 0.8, 0.8, 0.7])

13. 积分 >= 1000: 折扣 0.7
积分 >= 500: 折扣 0.8
积分 >= 100: 折扣 0.9
否则: 折扣 1.0

In [43]:
price = np.array([100, 200, 500, 1000])
points = np.array([0, 100, 500, 1000])

In [45]:
result14 = np.select(
    [points >= 1000, points >= 500, points >= 100],
    [0.7, 0.8, 0.9],
    default=1.0
)

result14

array([1. , 0.9, 0.8, 0.7])

In [48]:
final_price = price * result14
final_price

array([100., 180., 400., 700.])

15.如果 订单金额 >= 100 或者 是会员，就免运费，运费为 0
否则运费为 20

In [49]:
amount = np.array([80, 120, 60, 200, 40])
is_member = np.array([True, False, True, False, True])

In [51]:
result15 = np.where((amount >= 100) | is_member, 0, 20)
result15

array([0, 0, 0, 0, 0])

16.如果 订单金额 >= 100 并且 是会员，打 8 折；
否则原价。

In [52]:
amount = np.array([80, 120, 60, 200, 40])
is_member = np.array([True, False, True, False, True])

In [53]:
result16 = np.where((amount >= 100) & is_member, amount * 0.8, amount)
result16

array([ 80., 120.,  60., 200.,  40.])

17.分数 >= 60 并且 出勤 >= 80，显示 'pass'
否则显示 'fail'

In [54]:
score = np.array([50, 60, 75, 90, 40])
attendance = np.array([80, 90, 70, 95, 100])

In [56]:
result17 = np.where((score >= 60) & (attendance >= 80), "pass", "fail")
result17

array(['fail', 'pass', 'fail', 'pass', 'fail'], dtype='<U4')

18.如果 满足以下任一条件，就显示 'discount'：
1. 订单金额 >= 100 并且 是会员
2. 有优惠券 coupon

否则显示 'no discount'

In [57]:
amount = np.array([50, 120, 80, 200, 30])
is_member = np.array([False, False, True, False, True])
coupon = np.array([True, False, False, True, False])

In [59]:
result18 = np.where(
    ((amount >= 100) & is_member)|coupon, "discount", "no discount"
)

result18

array(['discount', 'no discount', 'no discount', 'discount',
       'no discount'], dtype='<U11')

当然。下面是这节 **4.1 `where()`** 的整理版笔记，按“你以后复习能看懂”的方式写。

**NumPy 4.1 `where()` 笔记**

这一节讲的是：

```text
用 np.where() 代替 for 循环里的 if/else。
```

也就是：当你想对 NumPy 数组里的每个元素做判断时，不要一个一个循环，尽量让 NumPy 一次性处理。

核心公式：

```python
np.where(condition, value_if_true, value_if_false)
```

中文意思：

```text
如果 condition 为 True，就用 value_if_true；
如果 condition 为 False，就用 value_if_false。
```

例子：

```python
import numpy as np

foo = np.array([10, 20, 30, 40])
bar = np.array([1, 2, 3, 4])

baz = np.where(bar % 2 == 0, foo * 2, foo / 2)
baz
```

结果：

```python
array([ 5., 40., 15., 80.])
```

解释：

```text
bar = 1，是奇数，所以 foo = 10 / 2 = 5
bar = 2，是偶数，所以 foo = 20 * 2 = 40
bar = 3，是奇数，所以 foo = 30 / 2 = 15
bar = 4，是偶数，所以 foo = 40 * 2 = 80
```

普通慢写法是：

```python
baz = np.zeros(foo.size)

for i in range(foo.size):
    if bar[i] % 2 == 0:
        baz[i] = foo[i] * 2
    else:
        baz[i] = foo[i] / 2
```

这段代码没错，但是慢。因为 Python 是一轮一轮处理，每次循环都要和底层 C 代码来回沟通。

NumPy 快写法是：

```python
baz = np.where(bar % 2 == 0, foo * 2, foo / 2)
```

这叫 **vectorization，向量化**。

简单理解：

```text
for 循环：一个一个算
np.where：整批一起算
```

所以 NumPy 会快很多。

视频里对比速度：

```text
for 循环：大约 2.17 秒
np.where：大约 57 毫秒
```

`57 毫秒 = 0.057 秒`，所以 `np.where()` 快非常多。

视频还用了：

```python
np.array_equal(baz1, baz2)
```

作用是检查两个数组是否完全一样。

例如：

```python
np.array_equal(
    np.array([1, 2, 3]),
    np.array([1, 2, 3])
)
```

结果：

```python
True
```

在视频里，它用来证明：

```text
for 循环算出来的结果
```

和：

```text
np.where() 算出来的结果
```

是一样的，只是 `np.where()` 更快。

测速用的是 Jupyter 里的：

```python
%%timeit
```

它可以测一段代码的运行时间。

比如：

```python
%%timeit
np.where(bar % 2 == 0, foo * 2, foo / 2)
```

**本节最重要的记忆点**

看到这种逻辑：

```python
for i in range(...):
    if 条件:
        做 A
    else:
        做 B
```

如果处理的是 NumPy 数组，就优先想：

```python
np.where(条件, A, B)
```

你要背下来的句子：

```python
np.where(condition, yes, no)
```

意思是：

```text
条件成立选 yes，不成立选 no。
```

我们刚才额外练到的补充知识：

```python
(condition1) & (condition2)
```

表示“并且”。

```python
(condition1) | (condition2)
```

表示“或者”。

注意多个条件一定要加括号：

```python
(amount >= 100) | is_member
```

不要写成：

```python
amount >= 100 | is_member
```

这个容易算错。

下一步我们就严格回到这节课内容来练：  
**把 for + if/else 改写成 np.where()**。这才是 4.1 的核心能力。