In [1]:
import numpy as np

squee = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

题 1：全部求和
要求：把所有数字加起来。

In [2]:
result1 = np.sum(squee)
result1

np.int64(21)

题 2：按列求和

In [3]:
result2 = np.sum(squee, axis = 0)
result2

array([5, 7, 9])

题 3：按行求和

In [4]:
result3 = np.sum(squee, axis = 1)
result3

array([ 6, 15])

题 4：按列求和，但保留二维

In [7]:
result4 = np.sum(squee, axis=0, keepdims=True)
result4.shape

(1, 3)

题 5：按行求和，但保留二维

In [6]:
result5 = np.sum(squee, axis=1, keepdims=True)
result5

array([[ 6],
       [15]])

In [8]:
result5.shape

(2, 1)

In [9]:
squee = np.array([
    [1., 2., 3.],
    [4., 5., 6.]
])


In [11]:
squee[0,0] = np.nan
squee

array([[nan,  2.,  3.],
       [ 4.,  5.,  6.]])

In [13]:
result6 = np.sum(squee)
result6

np.float64(nan)

In [14]:
result7 = np.nansum(squee)
result7

np.float64(20.0)

In [15]:
result8 = np.sum(np.nan_to_num(squee))
result8

np.float64(20.0)

题 1：全部求和

In [16]:
import numpy as np

arr = np.array([
    [2., 4., 6.],
    [1., 3., 5.]
])

In [17]:
result9 = np.sum(arr)
result9

np.float64(21.0)

题 2：按列求和

In [21]:
result10 = np.sum(arr, axis=0)
result10

array([ 3.,  7., 11.])

题 3：按行求和

In [22]:
result11 = np.sum(arr, axis=1)
result11

array([12.,  9.])

In [24]:
result11.shape

(2,)

题 4：按列求和，保留二维

In [25]:
result12 = np.sum(arr, axis=0, keepdims=True)
result12

array([[ 3.,  7., 11.]])

In [26]:
result12.shape

(1, 3)

题 5：按行求和，保留二维

In [27]:
result13 = np.sum(arr, axis=1, keepdims=True)
result13

array([[12.],
       [ 9.]])

In [28]:
result13.shape

(2, 1)

In [30]:
arr_nan = np.array([
    [np.nan, 4., 6.],
    [1., 3., 5.]
])

In [32]:
result14 = np.nansum(arr_nan)
result14

np.float64(19.0)

题 8：用 np.nansum() 按列求和

In [33]:
result15 = np.nansum(arr_nan, axis=0)
result15

array([ 1.,  7., 11.])

题 9：用 np.nansum() 按行求和

In [34]:
result16 = np.nansum(arr_nan, axis=1)
result16

array([10.,  9.])

题 10：全部销售额

In [35]:
sales = np.array([
    [100., 200., np.nan],
    [50., np.nan, 150.],
    [80., 120., 100.]
])

In [36]:
result17 = np.nansum(sales)
result17

np.float64(800.0)

题 11：每个商品总销售额

In [38]:
result18 = np.nansum(sales, axis=0)
result18

array([230., 320., 250.])

题 12：每天总销售额

In [39]:
result19 = np.nansum(sales, axis=1)
result19

array([300., 200., 300.])