In [1]:
import numpy as np

roux = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

gumbo = np.array([
    [10, 20],
    [30, 40]
])

In [2]:
roux.shape

(3, 2)

In [3]:
gumbo.shape

(2, 2)

题 1：上下拼 roux 和 gumbo

In [4]:
result1 = np.concatenate([roux,gumbo], axis=0)
result1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 20],
       [30, 40]])

题 2：左右拼 roux 和 gumbo
不能拼，左右拼看行 3，2 不同

题 3：roux 和 roux 上下拼

In [5]:
result2 = np.concatenate([roux,roux], axis = 0)
result2

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4],
       [5, 6]])

In [6]:
result2.shape

(6, 2)

题 4：roux 和 roux 左右拼

In [7]:
result3 = np.concatenate([roux, roux], axis = 1)
result3

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6]])

In [8]:
result3.shape

(3, 4)

In [9]:
a = np.ones((2, 3))
b = np.ones((2, 5))

In [10]:
a.shape

(2, 3)

In [11]:
b.shape

(2, 5)

np.concatenate([a, b], axis=0)

不能 列不同， 3/5

np.concatenate([a, b], axis=1)

可以，左右，增加列数， 最后shape是（2，8）



In [12]:
c = np.ones((4, 3))
d = np.ones((2, 3))

In [13]:
c.shape

(4, 3)

In [14]:
d.shape

(2, 3)

np.concatenate([c, d], axis=0)

可以，增加的是行数，最后是 （6，3）

np.concatenate([c, d], axis=1)

不可以，增加的是列数，行数要一样， 4 2 不同

In [15]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

y = np.array([
    [10, 20, 30]
])

题 9：创建并拼接 要求：把 y 拼到 x 的下面。

In [17]:
result9 = np.concatenate([x,y], axis = 0)

In [18]:
result9

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [19]:
result9.shape

(3, 3)

题 10：把一列拼到右边, 要求：把 z 拼到 x 的右边。

In [20]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

z = np.array([
    [100],
    [200]
])

In [21]:
result10 = np.concatenate([x,z], axis=1)

In [22]:
result10

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200]])

In [23]:
result10.shape

(2, 4)

题 11：三个数组上下拼

In [24]:
a = np.array([
    [1, 2]
])

b = np.array([
    [3, 4],
    [5, 6]
])

c = np.array([
    [7, 8]
])

In [25]:
result11 = np.concatenate([a,b,c], axis=0)

In [27]:
result11.shape

(4, 2)

最后补一个容易犯错的点：1D 数组和 2D 数组不能随便拼, 维度看外层括号，或者ndim

In [28]:
result11.ndim

2